"""add_name_to_users

Revision ID: f6d6325672ec
Revises: 5f69628aa33d
Create Date: 2026-05-21 10:42:44.249280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f6d6325672ec'
down_revision: Union[str, None] = '5f69628aa33d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
